# Generated by Django 3.0.3 on 2020-05-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('dateTimeCreated', models.DateTimeField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fistname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('phoneNumber', models.IntegerField()),
                ('dateTimeCreated', models.DateTimeField(max_length=30)),
                ('amountOutstanding', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=70)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('dateTimeCreated', models.DateTimeField(max_length=30)),
                ('vendorid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectuser', models.CharField(max_length=30)),
                ('message', models.TextField(max_length=70)),
                ('dateTimeCreated', models.DateTimeField(max_length=30)),
                ('messageStatus', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Order_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderInitiator', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=70)),
                ('itemsOrdered', models.TextField(max_length=100)),
                ('amountDue', models.FloatField()),
                ('amountPaid', models.FloatField()),
                ('amounntOutstanding', models.FloatField()),
                ('orderStatus', models.CharField(max_length=30)),
                ('dateAndTimeOfOrder', models.DateField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessName', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('phoneNumber', models.IntegerField()),
                ('dateTimeCreated', models.DateTimeField(max_length=30)),
            ],
        ),
    ]
