# Generated by Django 3.0.3 on 2020-05-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='Customer',
            new_name='Customer_Table',
        ),
        migrations.RenameModel(
            old_name='Notification_table',
            new_name='Notifications_Table',
        ),
        migrations.RenameModel(
            old_name='Vendor',
            new_name='Vendor_Table',
        ),
    ]
