# Generated by Django 3.0.3 on 2020-05-18 12:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eatery', '0002_auto_20200505_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('dateTimeCreated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=10)),
                ('fistname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=50)),
                ('dateTimeCreated', models.DateTimeField(max_length=30)),
                ('amountOutstanding', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='MenuTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('dateTimeCreated', models.DateTimeField(default=datetime.datetime(2020, 5, 18, 13, 0, 8, 44169), verbose_name='date created')),
                ('vendorid', models.IntegerField()),
                ('isRecurring', models.CharField(max_length=10)),
                ('frequencyOfReocurrance', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MessageStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=50)),
                ('subjectuser', models.CharField(max_length=30)),
                ('dateTimeCreated', models.DateTimeField(default=datetime.datetime(2020, 5, 18, 13, 0, 8, 50169), verbose_name='date sent')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='OrderTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=50)),
                ('customerid', models.CharField(blank=True, max_length=70)),
                ('description', models.TextField()),
                ('amountDue', models.FloatField()),
                ('amountPaid', models.FloatField()),
                ('amountOutstanding', models.FloatField()),
                ('dateAndTimeOfOrder', models.DateField()),
                ('itemsOrdered', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='eatery.MenuTable')),
                ('orderStatus', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='eatery.OrderStatus')),
            ],
        ),
        migrations.CreateModel(
            name='VendorTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=10)),
                ('businessName', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('phoneNumber', models.IntegerField()),
                ('dateTimeCreated', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Vendor',
            },
        ),
        migrations.DeleteModel(
            name='Auth_table',
        ),
        migrations.DeleteModel(
            name='Customer_Table',
        ),
        migrations.DeleteModel(
            name='Menu_table',
        ),
        migrations.DeleteModel(
            name='Message_Status',
        ),
        migrations.DeleteModel(
            name='Notifications_Table',
        ),
        migrations.DeleteModel(
            name='Order_Status',
        ),
        migrations.DeleteModel(
            name='Order_table',
        ),
        migrations.DeleteModel(
            name='Vendor_Table',
        ),
        migrations.AddField(
            model_name='ordertable',
            name='vendorid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='eatery.VendorTable'),
        ),
        migrations.AddField(
            model_name='notificationstable',
            name='message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='eatery.OrderTable'),
        ),
        migrations.AddField(
            model_name='notificationstable',
            name='messageStatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='eatery.MessageStatus'),
        ),
        migrations.AddField(
            model_name='notificationstable',
            name='orderid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='eatery.CustomerTable'),
        ),
    ]
